# Numpy 
- Numpy is a fundamental library for scientific computing in Python. it provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basis of Numpy,focusing on arrays and vectorized operations.

In [1]:
import numpy as np

In [4]:
##create arrays using numpy
## createa 10 array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
# 1D - array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [10]:
# 2D -array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [17]:
## Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

## element wise addition
print("Addition:", arr1+arr2)

## substraction
print("Substraction:", arr1-arr2)

## multiplication
print("multiplication:",arr1 * arr2)

## divide
print("Divide:", arr1/ arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
Divide: [0.1 0.1 0.1 0.1 0.1]


In [23]:
## universal function
arr = np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
## array slicing and indexing
arr= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
arr[0][0]
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [72]:
arr[-2:]
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [68]:
arr[1:2]

array([[5, 6, 7, 8]])

In [75]:
# modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [76]:
arr[2,3] = 50
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  50]]


In [77]:
arr[1:]= 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [78]:
arr[1:2]= 30
print(arr)

[[100   2   3   4]
 [ 30  30  30  30]
 [100 100 100 100]]


In [79]:
arr[0:1]= 20
print(arr)

[[ 20  20  20  20]
 [ 30  30  30  30]
 [100 100 100 100]]


In [80]:
arr[0:2]= 10
print(arr)

[[ 10  10  10  10]
 [ 10  10  10  10]
 [100 100 100 100]]


In [81]:
arr[1]= 9
print(arr)

[[ 10  10  10  10]
 [  9   9   9   9]
 [100 100 100 100]]


In [83]:
arr[3] = 5
print(arr)  ## only index 2 rows 

IndexError: index 3 is out of bounds for axis 0 with size 3

In [88]:
## Statistical concept -- noramalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev= np.std(data)

 # normalize the data
normalized_data= (data - mean)/ std_dev
print("Noramlized data:", normalized_data)

Noramlized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [95]:
data1= np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean = np.mean(data1)
print("Mean:", mean)

# median
median = np.median(data1)
print("Median:", median)

# Standard deviation
std_dev = np.std(data1)
print("Standard deviation:", std_dev)

# Variance
variance = np.var(data1)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [100]:
## Logicalm operation
data1[data1 > 5]

array([ 6,  7,  8,  9, 10])

In [101]:
data1[(data1>=5) & (data1>=8)]

array([ 8,  9, 10])